# Generated by Django 2.2.13 on 2023-05-03 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0, tzinfo=utc))),
                ('ack_time', models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0, tzinfo=utc))),
                ('pull_time', models.IntegerField(default=0)),
                ('run_time', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('finished', models.BooleanField(default=False)),
                ('corr_id', models.UUIDField(db_index=True, default=0)),
                ('response', models.TextField(default='')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Services')),
            ],
        ),
    ]
